const icons: Object = {
  street: 'assets/icons/street.png',
  number: 'assets/icons/number.png',
  neighborhood: 'assets/icons/neighborhood.png',
  city: 'assets/icons/city.png',
  uf: 'assets/icons/uf.png',
  country: 'assets/icons/country.png',
  bedroom: 'assets/icons/bedroom.png',
  bathroom: 'assets/icons/bathroom.png',
  kitchen: 'assets/icons/kitchen.png',
  spot: 'assets/icons/spot.png',
  area: 'assets/icons/number.png',
  externalArea: 'assets/icons/outside.png',
  price: 'assets/icons/money.png',
  title: 'assets/icons/title.png',
  description: 'assets/icons/description.png',
  contactNumber: 'assets/icons/phoneNumber.png',
  contactEmail: 'assets/icons/email.png',
  url: 'assets/icons/cloud.svg',
  close: 'assets/icons/close.png',
  password: 'assets/icons/password.png',
  facebook: 'assets/icons/facebook.png',
  google: 'assets/icons/google.png',
  personWhite: 'assets/icons/personWhite.png',
  personBlack: 'assets/icons/personBlack.png',
  visible: 'assets/icons/visible.png',
  invisible: 'assets/icons/invisible.png',
  search: 'assets/icons/search.png'
}

export default icons;
